# Generated by Django 2.0.3 on 2018-03-21 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc', models.BooleanField(default=False)),
                ('college_id', models.BooleanField(default=False)),
                ('is_acco', models.BooleanField(default=False)),
                ('kit_issued', models.BooleanField(default=False)),
                ('id_issued', models.BooleanField(default=False)),
                ('caution', models.BooleanField(default=False)),
                ('bhawan', models.CharField(blank=True, max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=100)),
                ('controls1_at', models.DateTimeField(default=datetime.datetime.now)),
                ('controls2_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cogni_id', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('is_workshop_payment_done', models.BooleanField(default=False)),
                ('is_central_payement_done', models.BooleanField(default=False)),
                ('events', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('decription', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepts', to='controls.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='controls.Participant'),
        ),
    ]
