# Generated by Django 2.0.3 on 2018-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='controls1_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='controls2_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
