# Generated by Django 2.0.3 on 2018-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20180321_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='controls1_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='controls2_at',
            field=models.DateTimeField(null=True),
        ),
    ]
