# Generated by Django 2.0.3 on 2018-03-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_auto_20180321_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
    ]
