# Generated by Django 2.0.3 on 2018-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_remove_participant_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
    ]
