# Generated by Django 2.0.3 on 2018-03-24 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_reciept_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='controls3_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
